// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5pNeP4s5f3WF8Du6_oVTNce7vykswgc0',
    appId: '1:325353125400:web:ec39a0e67e20769d9a356d',
    messagingSenderId: '325353125400',
    projectId: 'pawpoint-8822d',
    authDomain: 'pawpoint-8822d.firebaseapp.com',
    storageBucket: 'pawpoint-8822d.firebasestorage.app',
    measurementId: 'G-P8Q6RE577H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChKD0gpZPQ-KSiaZaZmubJ1oJLhjKbDC0',
    appId: '1:325353125400:android:1931caad45aa895c9a356d',
    messagingSenderId: '325353125400',
    projectId: 'pawpoint-8822d',
    storageBucket: 'pawpoint-8822d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-lHS9oGOqXPMAuLzCInNsLYL4OvjvT0',
    appId: '1:325353125400:ios:6dfca9294a2ac2e79a356d',
    messagingSenderId: '325353125400',
    projectId: 'pawpoint-8822d',
    storageBucket: 'pawpoint-8822d.firebasestorage.app',
    iosBundleId: 'com.example.pawpointAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-lHS9oGOqXPMAuLzCInNsLYL4OvjvT0',
    appId: '1:325353125400:ios:6dfca9294a2ac2e79a356d',
    messagingSenderId: '325353125400',
    projectId: 'pawpoint-8822d',
    storageBucket: 'pawpoint-8822d.firebasestorage.app',
    iosBundleId: 'com.example.pawpointAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5pNeP4s5f3WF8Du6_oVTNce7vykswgc0',
    appId: '1:325353125400:web:1647fc66cc99a55e9a356d',
    messagingSenderId: '325353125400',
    projectId: 'pawpoint-8822d',
    authDomain: 'pawpoint-8822d.firebaseapp.com',
    storageBucket: 'pawpoint-8822d.firebasestorage.app',
    measurementId: 'G-JK33X6H63P',
  );
}
